create table address(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	ip_address text,
	time DATE
);

insert into address(ip_address, time)
values ('196.117.5.252', NOW());


select * from address;

drop  table address;